import Head from 'next/head'
import Layout from '@/components/layout'
import client from '@/modules/contentfulClient'
import Img from '@/components/img'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout page='Home'>
        <p>
          Welcome to MUNDIES WORLD! 
        </p>
        <div className='relative w-[400px] h-[600px]'>
          <Img src='/mundies.png'/>
        </div>
      </Layout>
    </>
  )
}


export async function getServerSideProps() {
  try {
      const data = await client.getEntries({ content_type: 'test' })
    
      return { props: { data: data.items[0] } }
  } catch (err) {
      console.log(err)
      return {
          notFound: true
      }
  }
}