import Head from 'next/head'
import client from '../modules/contentfulClient'

export default function Home({ data }) {

  console.log(data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </>
  )
}


export async function getServerSideProps() {
  try {
      const data = await client.getEntries({ content_type: 'test' })
    
      return { props: { data: data.items[0] } }
  } catch (err) {
      console.log(err)
      return {
          notFound: true
      }
  }
}